version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build . -t example

     # deploy the image
     - run: docker run example sh -c "go test"